items:
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1
  commentId: T:System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1
  id: ConfiguredTaskAwaitable`1
  parent: System.Runtime.CompilerServices
  children:
  - System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.GetAwaiter
  langs:
  - csharp
  - vb
  name: ConfiguredTaskAwaitable<TResult>
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>
  type: Struct
  source:
    remote:
      path: src/System.Threading.Tasks/ref/System.Threading.Tasks.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: ConfiguredTaskAwaitable
    path: src/System.Threading.Tasks/ref/System.Threading.Tasks.cs
    startLine: 87
  assemblies:
  - System.Threading.Tasks
  namespace: System.Runtime.CompilerServices
  summary: "\n<p>Provides an awaitable object that enables configured awaits on a task.</p>\n"
  remarks: "\n<p>This type is intended for compiler use; do not use it directly in your code.</p>\n"
  syntax:
    content: public struct ConfiguredTaskAwaitable<TResult>
    content.vb: Public Structure ConfiguredTaskAwaitable(Of TResult)
    typeParameters:
    - id: TResult
      description: "\n<p>The type of the result produced by this <xref href=\"System.Threading.Tasks.Task`1\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n"
  modifiers.csharp:
  - public
  - struct
  modifiers.vb:
  - Public
  - Structure
  fullName.vb: System.Runtime.CompilerServices.ConfiguredTaskAwaitable(Of TResult)
  name.vb: ConfiguredTaskAwaitable(Of TResult)
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.GetAwaiter
  commentId: M:System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.GetAwaiter
  id: GetAwaiter
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1
  langs:
  - csharp
  - vb
  name: GetAwaiter()
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>.GetAwaiter()
  type: Method
  source:
    remote:
      path: src/System.Threading.Tasks/ref/System.Threading.Tasks.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: GetAwaiter
    path: src/System.Threading.Tasks/ref/System.Threading.Tasks.cs
    startLine: 90
  assemblies:
  - System.Threading.Tasks
  namespace: System.Runtime.CompilerServices
  summary: "\n<p>Returns an awaiter for this awaitable object.</p>\n"
  remarks: "\n<p>This method is intended for compiler use; do not use it directly in your code.</p>\n"
  syntax:
    content: public ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter GetAwaiter()
    content.vb: Public Function GetAwaiter As ConfiguredTaskAwaitable(Of TResult).ConfiguredTaskAwaiter
    return:
      type: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter
      description: "\n<p>The awaiter.</p>\n"
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: System.Runtime.CompilerServices.ConfiguredTaskAwaitable(Of TResult).GetAwaiter()
references:
- uid: System.Runtime.CompilerServices
  isExternal: false
  name: System.Runtime.CompilerServices
  fullName: System.Runtime.CompilerServices
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter
  parent: System.Runtime.CompilerServices
  isExternal: false
  name: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter<>
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter<>
  fullname.vb: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter(Of )
  name.vb: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter(Of )
  spec.csharp:
  - uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter
    name: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
    fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  - name: <
    fullName: <
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter
    name: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
    fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  - name: '(Of '
    fullName: '(Of '
  - name: )
    fullName: )
