items:
- uid: System.Security
  commentId: N:System.Security
  id: System.Security
  children:
  - System.Security.AllowPartiallyTrustedCallersAttribute
  - System.Security.SecureString
  - System.Security.SecureStringMarshal
  - System.Security.SecurityCriticalAttribute
  - System.Security.SecurityException
  - System.Security.SecuritySafeCriticalAttribute
  - System.Security.SecurityTransparentAttribute
  - System.Security.VerificationException
  langs:
  - csharp
  - vb
  name: System.Security
  fullName: System.Security
  type: Namespace
  assemblies:
  - System.Runtime
references:
- uid: System.Security.AllowPartiallyTrustedCallersAttribute
  isExternal: false
  name: AllowPartiallyTrustedCallersAttribute
  fullName: System.Security.AllowPartiallyTrustedCallersAttribute
- uid: System.Security.SecurityCriticalAttribute
  parent: System.Security
  isExternal: false
  name: SecurityCriticalAttribute
  fullName: System.Security.SecurityCriticalAttribute
- uid: System.Security.SecurityException
  isExternal: false
  name: SecurityException
  fullName: System.Security.SecurityException
- uid: System.Security.SecuritySafeCriticalAttribute
  parent: System.Security
  isExternal: false
  name: SecuritySafeCriticalAttribute
  fullName: System.Security.SecuritySafeCriticalAttribute
- uid: System.Security.SecurityTransparentAttribute
  isExternal: false
  name: SecurityTransparentAttribute
  fullName: System.Security.SecurityTransparentAttribute
- uid: System.Security.VerificationException
  isExternal: false
  name: VerificationException
  fullName: System.Security.VerificationException
- uid: System.Security.SecureString
  parent: System.Security
  isExternal: false
  name: SecureString
  fullName: System.Security.SecureString
- uid: System.Security.SecureStringMarshal
  isExternal: false
  name: SecureStringMarshal
  fullName: System.Security.SecureStringMarshal
- uid: System.Security
  isExternal: false
  name: System.Security
  fullName: System.Security
