items:
- uid: System.Data.SqlClient.ApplicationIntent
  commentId: T:System.Data.SqlClient.ApplicationIntent
  id: ApplicationIntent
  parent: System.Data.SqlClient
  children:
  - System.Data.SqlClient.ApplicationIntent.ReadOnly
  - System.Data.SqlClient.ApplicationIntent.ReadWrite
  langs:
  - csharp
  - vb
  name: ApplicationIntent
  fullName: System.Data.SqlClient.ApplicationIntent
  type: Enum
  source:
    remote:
      path: src/System.Data.SqlClient/src/System/Data/SqlClient/ApplicationIntent.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: ApplicationIntent
    path: src/System.Data.SqlClient/src/System/Data/SqlClient/ApplicationIntent.cs
    startLine: 12
  assemblies:
  - System.Data.SqlClient
  namespace: System.Data.SqlClient
  summary: "\n<p>Specifies a value for <xref href=\"System.Data.SqlClient.SqlConnectionStringBuilder.ApplicationIntent\" data-throw-if-not-resolved=\"false\"></xref>. Possible values are <strong>ReadWrite</strong> and <strong>ReadOnly</strong>.</p>\n"
  syntax:
    content: public enum ApplicationIntent
    content.vb: Public Enum ApplicationIntent
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: System.Data.SqlClient.ApplicationIntent.ReadOnly
  commentId: F:System.Data.SqlClient.ApplicationIntent.ReadOnly
  id: ReadOnly
  parent: System.Data.SqlClient.ApplicationIntent
  langs:
  - csharp
  - vb
  name: ReadOnly
  fullName: System.Data.SqlClient.ApplicationIntent.ReadOnly
  type: Field
  source:
    remote:
      path: src/System.Data.SqlClient/src/System/Data/SqlClient/ApplicationIntent.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: ReadOnly
    path: src/System.Data.SqlClient/src/System/Data/SqlClient/ApplicationIntent.cs
    startLine: 15
  assemblies:
  - System.Data.SqlClient
  namespace: System.Data.SqlClient
  summary: "\n<p>The application workload type when connecting to a server is read only.</p>\n"
  syntax:
    content: ReadOnly = 1
    return:
      type: System.Data.SqlClient.ApplicationIntent
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: System.Data.SqlClient.ApplicationIntent.ReadWrite
  commentId: F:System.Data.SqlClient.ApplicationIntent.ReadWrite
  id: ReadWrite
  parent: System.Data.SqlClient.ApplicationIntent
  langs:
  - csharp
  - vb
  name: ReadWrite
  fullName: System.Data.SqlClient.ApplicationIntent.ReadWrite
  type: Field
  source:
    remote:
      path: src/System.Data.SqlClient/src/System/Data/SqlClient/ApplicationIntent.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: ReadWrite
    path: src/System.Data.SqlClient/src/System/Data/SqlClient/ApplicationIntent.cs
    startLine: 14
  assemblies:
  - System.Data.SqlClient
  namespace: System.Data.SqlClient
  summary: "\n<p>The application workload type when connecting to a server is read write.</p>\n"
  syntax:
    content: ReadWrite = 0
    return:
      type: System.Data.SqlClient.ApplicationIntent
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: System.Data.SqlClient
  isExternal: false
  name: System.Data.SqlClient
  fullName: System.Data.SqlClient
- uid: System.Data.SqlClient.ApplicationIntent
  parent: System.Data.SqlClient
  isExternal: false
  name: ApplicationIntent
  fullName: System.Data.SqlClient.ApplicationIntent
