items:
- uid: Windows.UI.Xaml.Automation
  commentId: N:Windows.UI.Xaml.Automation
  id: Windows.UI.Xaml.Automation
  children:
  - Windows.UI.Xaml.Automation.ElementNotAvailableException
  - Windows.UI.Xaml.Automation.ElementNotEnabledException
  langs:
  - csharp
  - vb
  name: Windows.UI.Xaml.Automation
  fullName: Windows.UI.Xaml.Automation
  type: Namespace
  assemblies:
  - System.Runtime.WindowsRuntime.UI.Xaml
  summary: 'The <xref href="Windows.UI.Xaml.Automation" data-throw-if-not-resolved="false"></xref> namespace contains types that support the development of Windows Store apps with the .NET Framework. '
references:
- uid: Windows.UI.Xaml.Automation.ElementNotAvailableException
  isExternal: false
  name: ElementNotAvailableException
  fullName: Windows.UI.Xaml.Automation.ElementNotAvailableException
- uid: Windows.UI.Xaml.Automation.ElementNotEnabledException
  isExternal: false
  name: ElementNotEnabledException
  fullName: Windows.UI.Xaml.Automation.ElementNotEnabledException
