items:
- uid: System.Diagnostics.Tracing.EventSourceSettings
  commentId: T:System.Diagnostics.Tracing.EventSourceSettings
  id: EventSourceSettings
  parent: System.Diagnostics.Tracing
  children:
  - System.Diagnostics.Tracing.EventSourceSettings.Default
  - System.Diagnostics.Tracing.EventSourceSettings.EtwManifestEventFormat
  - System.Diagnostics.Tracing.EventSourceSettings.EtwSelfDescribingEventFormat
  - System.Diagnostics.Tracing.EventSourceSettings.ThrowOnEventWriteErrors
  langs:
  - csharp
  - vb
  name: EventSourceSettings
  fullName: System.Diagnostics.Tracing.EventSourceSettings
  type: Enum
  source:
    remote:
      path: src/mscorlib/src/System/Diagnostics/Eventing/EventSource.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    id: EventSourceSettings
    path: src/mscorlib/src/System/Diagnostics/Eventing/EventSource.cs
    startLine: 4149
  assemblies:
  - System.Diagnostics.Tracing
  namespace: System.Diagnostics.Tracing
  summary: Specifies configuration options for an event source.
  syntax:
    content: 'public enum EventSourceSettings : int'
    content.vb: Public Enum EventSourceSettings As Integer
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: System.Diagnostics.Tracing.EventSourceSettings.Default
  commentId: F:System.Diagnostics.Tracing.EventSourceSettings.Default
  id: Default
  parent: System.Diagnostics.Tracing.EventSourceSettings
  langs:
  - csharp
  - vb
  name: Default
  fullName: System.Diagnostics.Tracing.EventSourceSettings.Default
  type: Field
  source:
    remote:
      path: src/mscorlib/src/System/Diagnostics/Eventing/EventSource.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    id: Default
    path: src/mscorlib/src/System/Diagnostics/Eventing/EventSource.cs
    startLine: 4155
  assemblies:
  - System.Diagnostics.Tracing
  namespace: System.Diagnostics.Tracing
  summary: None of the special configuration options are enabled.
  syntax:
    content: Default = null
    content.vb: Default = Nothing
    return:
      type: System.Diagnostics.Tracing.EventSourceSettings
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: System.Diagnostics.Tracing.EventSourceSettings.EtwManifestEventFormat
  commentId: F:System.Diagnostics.Tracing.EventSourceSettings.EtwManifestEventFormat
  id: EtwManifestEventFormat
  parent: System.Diagnostics.Tracing.EventSourceSettings
  langs:
  - csharp
  - vb
  name: EtwManifestEventFormat
  fullName: System.Diagnostics.Tracing.EventSourceSettings.EtwManifestEventFormat
  type: Field
  source:
    remote:
      path: src/mscorlib/src/System/Diagnostics/Eventing/EventSource.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    id: EtwManifestEventFormat
    path: src/mscorlib/src/System/Diagnostics/Eventing/EventSource.cs
    startLine: 4166
  assemblies:
  - System.Diagnostics.Tracing
  namespace: System.Diagnostics.Tracing
  summary: The ETW listener should use a manifest-based format when raising events. Setting this option is a directive to the ETW listener should use manifest-based format when raising events. This is the default option when defining a type derived from <xref href="System.Diagnostics.Tracing.EventSource" data-throw-if-not-resolved="false"></xref> using one of the protected <xref href="System.Diagnostics.Tracing.EventSource" data-throw-if-not-resolved="false"></xref> constructors.
  syntax:
    content: EtwManifestEventFormat = null
    content.vb: EtwManifestEventFormat = Nothing
    return:
      type: System.Diagnostics.Tracing.EventSourceSettings
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: System.Diagnostics.Tracing.EventSourceSettings.EtwSelfDescribingEventFormat
  commentId: F:System.Diagnostics.Tracing.EventSourceSettings.EtwSelfDescribingEventFormat
  id: EtwSelfDescribingEventFormat
  parent: System.Diagnostics.Tracing.EventSourceSettings
  langs:
  - csharp
  - vb
  name: EtwSelfDescribingEventFormat
  fullName: System.Diagnostics.Tracing.EventSourceSettings.EtwSelfDescribingEventFormat
  type: Field
  source:
    remote:
      path: src/mscorlib/src/System/Diagnostics/Eventing/EventSource.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    id: EtwSelfDescribingEventFormat
    path: src/mscorlib/src/System/Diagnostics/Eventing/EventSource.cs
    startLine: 4173
  assemblies:
  - System.Diagnostics.Tracing
  namespace: System.Diagnostics.Tracing
  summary: 'The ETW listener should use self-describing event format. This is the default option when creating a new instance of the <xref href="System.Diagnostics.Tracing.EventSource" data-throw-if-not-resolved="false"></xref> using one of the public <xref href="System.Diagnostics.Tracing.EventSource" data-throw-if-not-resolved="false"></xref> constructors. '
  syntax:
    content: EtwSelfDescribingEventFormat = null
    content.vb: EtwSelfDescribingEventFormat = Nothing
    return:
      type: System.Diagnostics.Tracing.EventSourceSettings
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: System.Diagnostics.Tracing.EventSourceSettings.ThrowOnEventWriteErrors
  commentId: F:System.Diagnostics.Tracing.EventSourceSettings.ThrowOnEventWriteErrors
  id: ThrowOnEventWriteErrors
  parent: System.Diagnostics.Tracing.EventSourceSettings
  langs:
  - csharp
  - vb
  name: ThrowOnEventWriteErrors
  fullName: System.Diagnostics.Tracing.EventSourceSettings.ThrowOnEventWriteErrors
  type: Field
  source:
    remote:
      path: src/mscorlib/src/System/Diagnostics/Eventing/EventSource.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    id: ThrowOnEventWriteErrors
    path: src/mscorlib/src/System/Diagnostics/Eventing/EventSource.cs
    startLine: 4159
  assemblies:
  - System.Diagnostics.Tracing
  namespace: System.Diagnostics.Tracing
  summary: 'The event source throws an exception when an error occurs. '
  syntax:
    content: ThrowOnEventWriteErrors = null
    content.vb: ThrowOnEventWriteErrors = Nothing
    return:
      type: System.Diagnostics.Tracing.EventSourceSettings
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: System.Diagnostics.Tracing
  isExternal: false
  name: System.Diagnostics.Tracing
  fullName: System.Diagnostics.Tracing
- uid: System.Diagnostics.Tracing.EventSourceSettings
  parent: System.Diagnostics.Tracing
  isExternal: false
  name: EventSourceSettings
  fullName: System.Diagnostics.Tracing.EventSourceSettings
