items:
- uid: System.ComponentModel.TypeConverter.StandardValuesCollection
  commentId: T:System.ComponentModel.TypeConverter.StandardValuesCollection
  id: TypeConverter.StandardValuesCollection
  parent: System.ComponentModel
  children:
  - System.ComponentModel.TypeConverter.StandardValuesCollection.#ctor(System.Collections.ICollection)
  - System.ComponentModel.TypeConverter.StandardValuesCollection.CopyTo(System.Array,System.Int32)
  - System.ComponentModel.TypeConverter.StandardValuesCollection.Count
  - System.ComponentModel.TypeConverter.StandardValuesCollection.GetEnumerator
  - System.ComponentModel.TypeConverter.StandardValuesCollection.Item(System.Int32)
  langs:
  - csharp
  - vb
  name: TypeConverter.StandardValuesCollection
  fullName: System.ComponentModel.TypeConverter.StandardValuesCollection
  type: Class
  source:
    remote:
      path: src/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeConverter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: StandardValuesCollection
    path: src/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeConverter.cs
    startLine: 526
  assemblies:
  - System.ComponentModel.TypeConverter
  namespace: System.ComponentModel
  summary: Represents a collection of values.
  syntax:
    content: 'public class StandardValuesCollection : Collections.ICollection, Collections.IEnumerable'
    content.vb: >-
      Public Class StandardValuesCollection
          Inherits Collections.ICollection
          Implements Collections.IEnumerable
  inheritance:
  - System.Object
  implements:
  - System.Collections.IEnumerable
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: System.ComponentModel.TypeConverter.StandardValuesCollection.#ctor(System.Collections.ICollection)
  commentId: M:System.ComponentModel.TypeConverter.StandardValuesCollection.#ctor(System.Collections.ICollection)
  id: '#ctor(System.Collections.ICollection)'
  parent: System.ComponentModel.TypeConverter.StandardValuesCollection
  langs:
  - csharp
  - vb
  name: StandardValuesCollection(Collections.ICollection)
  fullName: System.ComponentModel.TypeConverter.StandardValuesCollection.StandardValuesCollection(System.Collections.ICollection)
  type: Constructor
  source:
    remote:
      path: src/System.ComponentModel.TypeConverter/ref/System.ComponentModel.TypeConverter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.ComponentModel.TypeConverter/ref/System.ComponentModel.TypeConverter.cs
    startLine: 513
  assemblies:
  - System.ComponentModel.TypeConverter
  namespace: System.ComponentModel
  summary: Initializes a new instance of the <xref href="System.ComponentModel.TypeConverter.StandardValuesCollection" data-throw-if-not-resolved="false"></xref> class.
  syntax:
    content: public StandardValuesCollection(Collections.ICollection values)
    content.vb: Public Sub New(values As Collections.ICollection)
    parameters:
    - id: values
      type: System.Collections.ICollection
      description: 'An <xref href="System.Collections.ICollection" data-throw-if-not-resolved="false"></xref> that represents the objects to put into the collection. '
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.ComponentModel.TypeConverter.StandardValuesCollection.Count
  commentId: P:System.ComponentModel.TypeConverter.StandardValuesCollection.Count
  id: Count
  parent: System.ComponentModel.TypeConverter.StandardValuesCollection
  langs:
  - csharp
  - vb
  name: Count
  fullName: System.ComponentModel.TypeConverter.StandardValuesCollection.Count
  type: Property
  source:
    remote:
      path: src/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeConverter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: Count
    path: src/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeConverter.cs
    startLine: 557
  assemblies:
  - System.ComponentModel.TypeConverter
  namespace: System.ComponentModel
  summary: Gets the number of objects in the collection.
  syntax:
    content: public int Count { get; }
    content.vb: Public ReadOnly Property Count As Integer
    parameters: []
    return:
      type: System.Int32
      description: The number of objects in the collection.
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: System.ComponentModel.TypeConverter.StandardValuesCollection.Item(System.Int32)
  commentId: P:System.ComponentModel.TypeConverter.StandardValuesCollection.Item(System.Int32)
  id: Item(System.Int32)
  parent: System.ComponentModel.TypeConverter.StandardValuesCollection
  langs:
  - csharp
  - vb
  name: Item[Int32]
  fullName: System.ComponentModel.TypeConverter.StandardValuesCollection.Item[System.Int32]
  type: Property
  source:
    remote:
      path: src/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeConverter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: this[]
    path: src/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeConverter.cs
    startLine: 575
  assemblies:
  - System.ComponentModel.TypeConverter
  namespace: System.ComponentModel
  summary: Gets the object at the specified index number.
  syntax:
    content: public object this[int index] { get; }
    content.vb: Public ReadOnly Property Item(index As Integer) As Object
    parameters:
    - id: index
      type: System.Int32
      description: 'The zero-based index of the <xref href="System.Object" data-throw-if-not-resolved="false"></xref> to get from the collection. '
    return:
      type: System.Object
      description: The <xref href="System.Object" data-throw-if-not-resolved="false"></xref> with the specified index.
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
  fullName.vb: System.ComponentModel.TypeConverter.StandardValuesCollection.Item(System.Int32)
  name.vb: Item(Int32)
- uid: System.ComponentModel.TypeConverter.StandardValuesCollection.CopyTo(System.Array,System.Int32)
  commentId: M:System.ComponentModel.TypeConverter.StandardValuesCollection.CopyTo(System.Array,System.Int32)
  id: CopyTo(System.Array,System.Int32)
  parent: System.ComponentModel.TypeConverter.StandardValuesCollection
  langs:
  - csharp
  - vb
  name: CopyTo(Array, Int32)
  fullName: System.ComponentModel.TypeConverter.StandardValuesCollection.CopyTo(System.Array, System.Int32)
  type: Method
  source:
    remote:
      path: src/System.ComponentModel.TypeConverter/ref/System.ComponentModel.TypeConverter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: CopyTo
    path: src/System.ComponentModel.TypeConverter/ref/System.ComponentModel.TypeConverter.cs
    startLine: 518
  assemblies:
  - System.ComponentModel.TypeConverter
  namespace: System.ComponentModel
  summary: Copies the contents of this collection to an array.
  syntax:
    content: public void CopyTo(Array array, int index)
    content.vb: Public Sub CopyTo(array As Array, index As Integer)
    parameters:
    - id: array
      type: System.Array
      description: 'An <xref href="System.Array" data-throw-if-not-resolved="false"></xref> that represents the array to copy to. '
    - id: index
      type: System.Int32
      description: 'The index to start from. '
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.ComponentModel.TypeConverter.StandardValuesCollection.GetEnumerator
  commentId: M:System.ComponentModel.TypeConverter.StandardValuesCollection.GetEnumerator
  id: GetEnumerator
  parent: System.ComponentModel.TypeConverter.StandardValuesCollection
  langs:
  - csharp
  - vb
  name: GetEnumerator()
  fullName: System.ComponentModel.TypeConverter.StandardValuesCollection.GetEnumerator()
  type: Method
  source:
    remote:
      path: src/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeConverter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: GetEnumerator
    path: src/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeConverter.cs
    startLine: 611
  assemblies:
  - System.ComponentModel.TypeConverter
  namespace: System.ComponentModel
  summary: Returns an enumerator for this collection.
  syntax:
    content: public Collections.IEnumerator GetEnumerator()
    content.vb: Public Function GetEnumerator As Collections.IEnumerator
    return:
      type: System.Collections.IEnumerator
      description: An enumerator of type <xref href="System.Collections.IEnumerator" data-throw-if-not-resolved="false"></xref>.
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: System.ComponentModel
  isExternal: false
  name: System.ComponentModel
  fullName: System.ComponentModel
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  fullName: System.Object
- uid: System.Collections.IEnumerable
  parent: System.Collections
  isExternal: false
  name: IEnumerable
  fullName: System.Collections.IEnumerable
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Collections
  isExternal: false
  name: System.Collections
  fullName: System.Collections
- uid: System.Collections.ICollection
  parent: System.Collections
  isExternal: false
  name: ICollection
  fullName: System.Collections.ICollection
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  fullName: System.Int32
- uid: System.Array
  parent: System
  isExternal: false
  name: Array
  fullName: System.Array
- uid: System.Collections.IEnumerator
  parent: System.Collections
  isExternal: false
  name: Collections.IEnumerator
  fullName: System.Collections.IEnumerator
